import { Step } from "@shared/schema";

export const dsaSteps: Step[] = [
  {
    id: "step-1",
    stepNumber: 1,
    title: "Learn the basics",
    description: "Fundamentals of programming and basic concepts",
    totalProblems: 31,
    lectures: [
      {
        id: "lec-1-1",
        title: "Things to Know in C++/Java/Python or any language",
        problems: [
          {
            id: "user-input-output",
            title: "User Input / Output",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/c/c-basic-input-output/",
            youtubeUrl: "https://www.youtube.com/watch?v=EAR7De6Goz4",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/input-output",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/basic-input-output-c/",
          },
          {
            id: "data-types",
            title: "Data Types",
            difficulty: "Easy",
            youtubeUrl: "https://www.youtube.com/watch?v=EAR7De6Goz4",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/cpp",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/c-data-types/",
          },
          {
            id: "if-else-statements",
            title: "If Else statements",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/if-else/if-else-statements/",
            youtubeUrl: "https://www.youtube.com/watch?v=EAR7De6Goz4",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/if-elseif",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/decision-making-c-c-else-nested-else/",
          },
          {
            id: "switch-statement",
            title: "Switch Statement",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/switch-case/switch-case-statements/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/switch-case",
          },
          {
            id: "arrays-strings",
            title: "What are arrays, strings?",
            difficulty: "Easy",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/cpp",
          },
          {
            id: "for-loops",
            title: "For loops",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/for-loop/understanding-for-loop/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/cpp",
          },
          {
            id: "while-loops",
            title: "While loops",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/while-loop/while-loops-in-programming/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/cpp",
          },
          {
            id: "functions",
            title: "Functions (Pass by Reference and Value)",
            difficulty: "Easy",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/cpp",
          },
          {
            id: "time-complexity",
            title: "Time Complexity [Learn Basics, and then analyse in next Steps]",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/time-complexity/time-and-space-complexity-strivers-a2z-dsa-course/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
          },
        ],
      },
      {
        id: "lec-1-2",
        title: "Build-up Logical Thinking",
        problems: [
          {
            id: "patterns",
            title: "Patterns",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/easy-and-medium",
          },
        ],
      },
      {
        id: "lec-1-3",
        title: "Learn STL/Java-Collections or similar thing in your language",
        problems: [
          {
            id: "cpp-stl",
            title: "C++ STL",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
          },
          {
            id: "java-collections",
            title: "Java Collections",
            difficulty: "Easy",
          },
        ],
      },
      {
        id: "lec-1-4",
        title: "Know Basic Maths",
        problems: [
          {
            id: "count-digits",
            title: "Count Digits",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/count-digits-in-a-number/",
            youtubeUrl: "https://www.youtube.com/watch?v=1xNbjMdbjug",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/count-all-digits-of-a-number",
            leetcodeUrl: "https://leetcode.com/problems/number-of-digits-in-an-integer/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/program-count-digits-integer-3-different-methods/",
          },
          {
            id: "reverse-number",
            title: "Reverse a Number",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/maths/reverse-digits-of-a-number",
            youtubeUrl: "https://www.youtube.com/watch?v=1xNbjMdbjug",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/reverse-a-number",
            leetcodeUrl: "https://leetcode.com/problems/reverse-integer/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/write-a-program-to-reverse-digits-of-a-number/",
          },
          {
            id: "check-palindrome",
            title: "Check Palindrome",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/",
            youtubeUrl: "https://www.youtube.com/watch?v=1xNbjMdbjug",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/palindrome-number",
            leetcodeUrl: "https://leetcode.com/problems/palindrome-number/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/check-if-a-number-is-palindrome/",
          },
          {
            id: "gcd-hcf",
            title: "GCD Or HCF",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-gcd-of-two-numbers/",
            youtubeUrl: "https://www.youtube.com/watch?v=1xNbjMdbjug",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/gcd-of-two-numbers",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/c-program-find-gcd-hcf-two-numbers/",
          },
          {
            id: "armstrong-numbers",
            title: "Armstrong Numbers",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/maths/check-if-a-number-is-armstrong-number-or-not/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/check-if-the-number-if-armstrong",
            leetcodeUrl: "https://leetcode.com/problems/armstrong-numbers",
          },
          {
            id: "print-divisors",
            title: "Print all Divisors",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/print-all-divisors-of-a-given-number/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/sum-of-all-divisors",
          },
          {
            id: "prime-number",
            title: "Check for Prime",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/check-prime",
          },
        ],
      },
    ],
  },
  {
    id: "step-2",
    stepNumber: 2,
    title: "Learn Important Sorting Techniques",
    description: "Master all sorting algorithms and their implementations",
    totalProblems: 7,
    lectures: [
      {
        id: "lec-2-1",
        title: "Sorting-I",
        problems: [
          {
            id: "selection-sort",
            title: "Selection Sort",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/sorting/selection-sort-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=HGk_ypEuS24",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/selection-sort",
            leetcodeUrl: "https://leetcode.com/problems/sort-an-array/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/selection-sort/",
          },
          {
            id: "bubble-sort",
            title: "Bubble Sort",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/bubble-sort-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=HGk_ypEuS24",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/bubble-sort",
            leetcodeUrl: "https://leetcode.com/problems/sort-an-array/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/bubble-sort/",
          },
          {
            id: "insertion-sort",
            title: "Insertion Sort",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/insertion-sort-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=HGk_ypEuS24",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/insertion-sort",
            leetcodeUrl: "https://leetcode.com/problems/sort-an-array/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/insertion-sort/",
          },
        ],
      },
      {
        id: "lec-2-2",
        title: "Sorting-II",
        problems: [
          {
            id: "merge-sort",
            title: "Merge Sort",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/merge-sort-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/merge-sort",
          },
          {
            id: "recursive-bubble-sort",
            title: "Recursive Bubble Sort",
            difficulty: "Medium",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/recursive-bubble-sort",
          },
          {
            id: "recursive-insertion-sort",
            title: "Recursive Insertion Sort",
            difficulty: "Medium",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/recursive-insertion-sort",
          },
          {
            id: "quick-sort",
            title: "Quick Sort",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/quick-sort-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/quick-sort",
          },
        ],
      },
    ],
  },
  {
    id: "step-3",
    stepNumber: 3,
    title: "Solve Problems on Arrays [Easy → Medium → Hard]",
    description: "Comprehensive array problem solving journey",
    totalProblems: 40,
    lectures: [
      {
        id: "lec-3-1",
        title: "Easy",
        problems: [
          {
            id: "largest-element",
            title: "Largest Element in Array",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/largest-element-in-an-array",
          },
          {
            id: "second-largest",
            title: "Second Largest Element",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/second-largest-element-in-an-array-without-sorting",
          },
          {
            id: "check-sorted",
            title: "Check if Array is Sorted",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/check-if-array-is-sorted",
            leetcodeUrl: "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/",
          },
        ],
      },
      {
        id: "lec-3-2",
        title: "Medium",
        problems: [
          {
            id: "two-sum",
            title: "Two Sum",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/two-sum/",
          },
          {
            id: "sort-colors",
            title: "Sort Colors",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/sort-colors/",
          },
          {
            id: "majority-element",
            title: "Majority Element",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/majority-element/",
          },
        ],
      },
      {
        id: "lec-3-3",
        title: "Hard",
        problems: [
          {
            id: "pascal-triangle",
            title: "Pascal's Triangle",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/pascals-triangle/",
          },
          {
            id: "majority-element-n3",
            title: "Majority Elements (>N/3 times)",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/majority-elements-n-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/majority-element-ii/",
          },
          {
            id: "three-sum",
            title: "3 Sum",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/3sum/",
          },
          {
            id: "four-sum",
            title: "4 Sum",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/4-sum-find-quads-that-add-up-to-a-target-value/",
            youtubeUrl: "https://www.youtube.com/watch?v=video_id",
            leetcodeUrl: "https://leetcode.com/problems/4sum/",
          },
        ],
      },
    ],
  },
  {
    id: "step-4",
    stepNumber: 4,
    title: "Binary Search [1D, 2D Arrays, Search Space]",
    description: "Master binary search in all its forms",
    totalProblems: 32,
    lectures: [
      {
        id: "lec-4-1",
        title: "Learning BS on 1D Arrays",
        problems: [
          {
            id: "binary-search",
            title: "Binary Search",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/binary-search-explained/",
            youtubeUrl: "https://www.youtube.com/watch?v=MHf6awe89xw",
            leetcodeUrl: "https://leetcode.com/problems/binary-search/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-search/",
          },
          {
            id: "implement-lower-bound",
            title: "Implement Lower Bound",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/arrays/implement-lower-bound-bs-2/",
            youtubeUrl: "https://www.youtube.com/watch?v=MHf6awe89xw",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/implement-lower-bound",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/lower_bound-in-cpp/",
          },
          {
            id: "search-insert-position",
            title: "Search Insert Position",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/arrays/search-insert-position/",
            youtubeUrl: "https://www.youtube.com/watch?v=MHf6awe89xw",
            leetcodeUrl: "https://leetcode.com/problems/search-insert-position/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/search-insert-position-of-k-in-a-sorted-array/",
          },
        ],
      },
      {
        id: "lec-4-2", 
        title: "BS on Answers",
        problems: [
          {
            id: "find-nth-root",
            title: "Finding Nth Root of M",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/nth-root-of-m-using-binary-search/",
            youtubeUrl: "https://www.youtube.com/watch?v=WjpswYrS2nY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/nth-root-of-m",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-nth-root-m/",
          },
          {
            id: "koko-eating-bananas",
            title: "Koko Eating Bananas",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/binary-search/koko-eating-bananas/",
            youtubeUrl: "https://www.youtube.com/watch?v=WjpswYrS2nY",
            leetcodeUrl: "https://leetcode.com/problems/koko-eating-bananas/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/koko-eating-bananas/",
          },
        ],
      },
    ],
  },
  {
    id: "step-5",
    stepNumber: 5,
    title: "Strings [Basic and Medium]",
    description: "String manipulation and algorithms",
    totalProblems: 15,
    lectures: [
      {
        id: "lec-5-1",
        title: "Basic and Easy String Problems",
        problems: [
          {
            id: "remove-outermost-parentheses",
            title: "Remove Outermost Parentheses",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/remove-outermost-parentheses/",
            youtubeUrl: "https://www.youtube.com/watch?v=qmEyhcNT8KA",
            leetcodeUrl: "https://leetcode.com/problems/remove-outermost-parentheses/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/remove-outermost-parentheses/",
          },
          {
            id: "reverse-words",
            title: "Reverse Words in a String",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/reverse-words-in-a-string/",
            youtubeUrl: "https://www.youtube.com/watch?v=qmEyhcNT8KA",
            leetcodeUrl: "https://leetcode.com/problems/reverse-words-in-a-string/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/reverse-words-in-a-given-string/",
          },
          {
            id: "largest-odd-number",
            title: "Largest Odd Number in String",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-the-largest-odd-number-in-string/",
            youtubeUrl: "https://www.youtube.com/watch?v=qmEyhcNT8KA",
            leetcodeUrl: "https://leetcode.com/problems/largest-odd-number-in-string/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/largest-odd-number-string/",
          },
        ],
      },
      {
        id: "lec-5-2",
        title: "Medium String Problems",
        problems: [
          {
            id: "longest-palindromic-substring",
            title: "Longest Palindromic Substring",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/longest-palindromic-substring/",
            youtubeUrl: "https://www.youtube.com/watch?v=qmEyhcNT8KA",
            leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-substring/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-palindromic-substring/",
          },
          {
            id: "roman-to-integer",
            title: "Roman Number to Integer and vice versa",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/roman-number-to-integer-and-vice-versa/",
            youtubeUrl: "https://www.youtube.com/watch?v=qmEyhcNT8KA",
            leetcodeUrl: "https://leetcode.com/problems/roman-to-integer/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/converting-roman-numerals-decimal-lying-1-3999/",
          },
        ],
      },
    ],
  },
  {
    id: "step-6",
    stepNumber: 6,
    title: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems]",
    description: "Complete LinkedList mastery",
    totalProblems: 31,
    lectures: [
      {
        id: "lec-6-1",
        title: "Learn 1D LinkedList",
        problems: [
          {
            id: "introduction-to-linkedlist",
            title: "Introduction to LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/introduction-to-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=Nq7ok-OyEpg",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/introduction-to-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/data-structures/linked-list/",
          },
          {
            id: "inserting-node-linkedlist",
            title: "Inserting a node in LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/insert-node-at-the-beginning-of-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=Nq7ok-OyEpg",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/insert-node-at-the-beginning-of-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
          },
          {
            id: "deleting-node-linkedlist",
            title: "Deleting a node in LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/delete-node-of-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=Nq7ok-OyEpg",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/delete-node-of-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/linked-list-set-3-deleting-node/",
          },
        ],
      },
      {
        id: "lec-6-2",
        title: "Learn Doubly LinkedList",
        problems: [
          {
            id: "introduction-to-dll",
            title: "Introduction to Doubly LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/introduction-to-doubly-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=Nq7ok-OyEpg",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/introduction-to-doubly-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/data-structures/linked-list/doubly-linked-list/",
          },
          {
            id: "insert-at-end-dll",
            title: "Insert at end of Doubly LinkedList", 
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/insert-at-end-of-doubly-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=Nq7ok-OyEpg",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/insert-at-end-of-doubly-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/insert-node-end-doubly-linked-list/",
          },
        ],
      },
      {
        id: "lec-6-3",
        title: "Medium Problems of LL",
        problems: [
          {
            id: "middle-of-linkedlist",
            title: "Middle of LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=sGdwSH8RK-o",
            leetcodeUrl: "https://leetcode.com/problems/middle-of-the-linked-list/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/write-a-c-function-to-print-the-middle-of-the-linked-list/",
          },
          {
            id: "reverse-linkedlist",
            title: "Reverse a LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/reverse-a-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=sGdwSH8RK-o",
            leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
          },
          {
            id: "detect-cycle-linkedlist",
            title: "Detect a Cycle in LinkedList",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=sGdwSH8RK-o",
            leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/",
          },
        ],
      },
      {
        id: "lec-6-4",
        title: "Hard Problems of LL",
        problems: [
          {
            id: "reverse-nodes-k-group",
            title: "Reverse Nodes in k-Group",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/reverse-linked-list-in-groups-of-size-k/",
            youtubeUrl: "https://www.youtube.com/watch?v=sGdwSH8RK-o",
            leetcodeUrl: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/reverse-a-list-in-groups-of-given-size/",
          },
          {
            id: "rotate-linkedlist",
            title: "Rotate a LinkedList",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/rotate-a-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=sGdwSH8RK-o",
            leetcodeUrl: "https://leetcode.com/problems/rotate-list/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/rotate-a-linked-list/",
          },
        ],
      },
    ],
  },
  {
    id: "step-7",
    stepNumber: 7,
    title: "Recursion [PatternWise]",
    description: "Master recursion with patterns",
    totalProblems: 25,
    lectures: [
      {
        id: "lec-7-1",
        title: "Get a Strong Hold",
        problems: [
          {
            id: "understand-recursion",
            title: "Understand recursion by print something N times",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/recursion/understand-recursion-by-print-something-n-times/",
            youtubeUrl: "https://www.youtube.com/watch?v=yVdKa8dnKiE",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/print-n-times",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/recursion/",
          },
          {
            id: "print-1-to-n",
            title: "Print 1 To N Without Loop",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/recursion/print-1-to-n-without-loop/",
            youtubeUrl: "https://www.youtube.com/watch?v=yVdKa8dnKiE",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/print-1-to-n-without-loop",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/program-to-print-first-n-natural-numbers/",
          },
          {
            id: "print-n-to-1",
            title: "Print N to 1 without loop",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/recursion/print-n-to-1-without-loop/",
            youtubeUrl: "https://www.youtube.com/watch?v=yVdKa8dnKiE",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/print-n-to-1-without-loop",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/program-to-print-numbers-from-n-to-1-in-reverse-order/",
          },
        ],
      },
      {
        id: "lec-7-2",
        title: "Recursion on Subsequences",
        problems: [
          {
            id: "generate-all-subsequences",
            title: "Generate all binary strings",
            difficulty: "Medium", 
            tufUrl: "https://takeuforward.org/recursion/generate-all-binary-strings/",
            youtubeUrl: "https://www.youtube.com/watch?v=eQCS_v3bw0Q",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/generate-all-binary-strings",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/generate-binary-strings-without-consecutive-1s/",
          },
          {
            id: "generate-parentheses",
            title: "Generate Parentheses",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/recursion/generate-parentheses/",
            youtubeUrl: "https://www.youtube.com/watch?v=eQCS_v3bw0Q",
            leetcodeUrl: "https://leetcode.com/problems/generate-parentheses/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/print-all-combinations-of-balanced-parentheses/",
          },
        ],
      },
      {
        id: "lec-7-3",
        title: "Hard Problems",
        problems: [
          {
            id: "n-queens",
            title: "N-Queens",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/",
            youtubeUrl: "https://www.youtube.com/watch?v=i05Ju7AftcM",
            leetcodeUrl: "https://leetcode.com/problems/n-queens/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/",
          },
          {
            id: "sudoku-solver",
            title: "Sudoku Solver",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/sudoku-solver/",
            youtubeUrl: "https://www.youtube.com/watch?v=i05Ju7AftcM",
            leetcodeUrl: "https://leetcode.com/problems/sudoku-solver/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/sudoku-backtracking-7/",
          },
          {
            id: "word-break-ii",
            title: "Word Break II",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/word-break-ii/",
            youtubeUrl: "https://www.youtube.com/watch?v=i05Ju7AftcM",
            leetcodeUrl: "https://leetcode.com/problems/word-break-ii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/word-break-problem-using-backtracking/",
          },
        ],
      },
    ],
  },
  {
    id: "step-8",
    stepNumber: 8,
    title: "Bit Manipulation [Concepts and Problems]",
    description: "Master bitwise operations",
    totalProblems: 23,
    lectures: [
      {
        id: "lec-8-1",
        title: "Learn Bit Manipulation",
        problems: [
          {
            id: "intro-to-bit-manipulation",
            title: "Introduction to Bit Manipulation",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/bit-manipulation/introduction-to-bit-manipulation/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/bits-manipulation-important-tactics/",
          },
          {
            id: "check-ith-bit",
            title: "Check if the ith bit is set or not",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/bit-manipulation/check-if-the-ith-bit-is-set-or-not/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/check-if-the-ith-bit-is-set-or-not",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/check-whether-k-th-bit-set-not/",
          },
          {
            id: "set-ith-bit",
            title: "Set the ith bit",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/bit-manipulation/set-the-ith-bit/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/set-the-ith-bit",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/set-k-th-bit-given-number/",
          },
        ],
      },
      {
        id: "lec-8-2",
        title: "Interview Problems",
        problems: [
          {
            id: "power-of-two",
            title: "Power of 2",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/bit-manipulation/power-of-2/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            leetcodeUrl: "https://leetcode.com/problems/power-of-two/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/program-to-find-whether-a-no-is-power-of-two/",
          },
          {
            id: "count-set-bits",
            title: "Count the number of set bits",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/bit-manipulation/count-the-number-of-set-bits/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            leetcodeUrl: "https://leetcode.com/problems/number-of-1-bits/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/count-set-bits-in-an-integer/",
          },
          {
            id: "single-number",
            title: "Single Number",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            leetcodeUrl: "https://leetcode.com/problems/single-number/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-the-element-that-appears-once/",
          },
        ],
      },
      {
        id: "lec-8-3",
        title: "Advanced Problems",
        problems: [
          {
            id: "single-number-ii",
            title: "Single Number II",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-other-numbers-thrice/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            leetcodeUrl: "https://leetcode.com/problems/single-number-ii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-the-element-that-appears-once/",
          },
          {
            id: "xor-queries-subarray",
            title: "XOR Queries of a Subarray",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/bit-manipulation/xor-queries-of-a-subarray/",
            youtubeUrl: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            leetcodeUrl: "https://leetcode.com/problems/xor-queries-of-a-subarray/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/queries-to-find-xor-of-subarray-of-given-array/",
          },
        ],
      },
    ],
  },
  {
    id: "step-9",
    stepNumber: 9,
    title: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation]",
    description: "Complete stack and queue mastery",
    totalProblems: 30,
    lectures: [
      {
        id: "lec-9-1",
        title: "Learning",
        problems: [
          {
            id: "implement-stack-using-arrays",
            title: "Implement Stack using Arrays",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/implement-stack-using-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=GYptUgnIM_I",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/implement-stack-using-array",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/",
          },
          {
            id: "implement-queue-using-arrays",
            title: "Implement Queue using Arrays",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/implement-queue-using-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=GYptUgnIM_I",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/implement-queue-using-array",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/",
          },
          {
            id: "implement-stack-using-linkedlist",
            title: "Implement Stack using Linked List",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/implement-stack-using-linked-list/",
            youtubeUrl: "https://www.youtube.com/watch?v=GYptUgnIM_I",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/implement-stack-using-linked-list",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/implement-a-stack-using-singly-linked-list/",
          },
        ],
      },
      {
        id: "lec-9-2",
        title: "Prefix, Infix, PostFix Conversion Problems",
        problems: [
          {
            id: "infix-to-postfix",
            title: "Infix to Postfix Conversion using Stack",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/infix-to-postfix-conversion-using-stack/",
            youtubeUrl: "https://www.youtube.com/watch?v=4pIkuZAjbVs",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/infix-to-postfix-conversion-using-stack",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/stack-set-2-infix-to-postfix/",
          },
          {
            id: "prefix-to-infix",
            title: "Prefix to Infix Conversion",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/prefix-to-infix-conversion/",
            youtubeUrl: "https://www.youtube.com/watch?v=4pIkuZAjbVs",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/prefix-to-infix-conversion",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/prefix-infix-conversion/",
          },
        ],
      },
      {
        id: "lec-9-3",
        title: "Monotonic Stack/Queue Problems [VVV. Imp]",
        problems: [
          {
            id: "next-greater-element",
            title: "Next Greater Element",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/next-greater-element-using-stack/",
            youtubeUrl: "https://www.youtube.com/watch?v=Du881K7Jtk8",
            leetcodeUrl: "https://leetcode.com/problems/next-greater-element-i/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/next-greater-element/",
          },
          {
            id: "next-smaller-element",
            title: "Next Smaller Element",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/next-smaller-element-using-stack/",
            youtubeUrl: "https://www.youtube.com/watch?v=Du881K7Jtk8",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/next-smaller-element-using-stack",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/next-smaller-element/",
          },
          {
            id: "largest-rectangle-histogram",
            title: "Largest Rectangle in Histogram",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/",
            youtubeUrl: "https://www.youtube.com/watch?v=Du881K7Jtk8",
            leetcodeUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/largest-rectangle-under-histogram/",
          },
        ],
      },
      {
        id: "lec-9-4",
        title: "Implementation Problems",
        problems: [
          {
            id: "sliding-window-maximum",
            title: "Sliding Window Maximum",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/sliding-window-maximum/",
            youtubeUrl: "https://www.youtube.com/watch?v=Du881K7Jtk8",
            leetcodeUrl: "https://leetcode.com/problems/sliding-window-maximum/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/",
          },
          {
            id: "stock-span-problem",
            title: "The Stock Span Problem",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/stock-span-problem/",
            youtubeUrl: "https://www.youtube.com/watch?v=Du881K7Jtk8",
            leetcodeUrl: "https://leetcode.com/problems/online-stock-span/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/the-stock-span-problem/",
          },
        ],
      },
    ],
  },
  {
    id: "step-10",
    stepNumber: 10,
    title: "Sliding Window & Two Pointer Combined Problems",
    description: "Advanced two-pointer and sliding window techniques",
    totalProblems: 12,
    lectures: [
      {
        id: "lec-10-1", 
        title: "Medium Problems",
        problems: [
          {
            id: "longest-substring-without-repeat",
            title: "Longest Substring Without Repeating Characters",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/",
            youtubeUrl: "https://www.youtube.com/watch?v=qtVh-XEpsJo",
            leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/",
          },
          {
            id: "max-consecutive-ones-iii",
            title: "Max Consecutive Ones III",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/max-consecutive-ones-iii/",
            youtubeUrl: "https://www.youtube.com/watch?v=qtVh-XEpsJo", 
            leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-zeroes-to-be-flipped-so-that-number-of-consecutive-1s-is-maximized/",
          },
          {
            id: "fruit-into-baskets",
            title: "Fruit Into Baskets",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/fruit-into-baskets/",
            youtubeUrl: "https://www.youtube.com/watch?v=qtVh-XEpsJo",
            leetcodeUrl: "https://leetcode.com/problems/fruit-into-baskets/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-subarray-having-count-distinct-elements-equal-k/",
          },
        ],
      },
      {
        id: "lec-10-2",
        title: "Hard Problems", 
        problems: [
          {
            id: "minimum-window-substring",
            title: "Minimum Window Substring",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/minimum-window-substring/",
            youtubeUrl: "https://www.youtube.com/watch?v=qtVh-XEpsJo",
            leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/",
          },
          {
            id: "subarrays-with-k-different", 
            title: "Subarrays with K Different Integers",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/subarrays-with-k-different-integers/",
            youtubeUrl: "https://www.youtube.com/watch?v=qtVh-XEpsJo",
            leetcodeUrl: "https://leetcode.com/problems/subarrays-with-k-different-integers/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/subarrays-with-k-distinct-elements/",
          },
        ],
      },
    ],
  },
  {
    id: "step-11",
    stepNumber: 11,
    title: "Heaps [Learning, Medium, Hard Problems]",
    description: "Master heap data structure and priority queues",
    totalProblems: 17,
    lectures: [
      {
        id: "lec-11-1",
        title: "Learning",
        problems: [
          {
            id: "intro-to-priority-queues", 
            title: "Introduction to Priority Queues using Binary Heaps",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/introduction-to-priority-queues-using-binary-heaps/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/priority-queue-set-1-introduction/",
          },
          {
            id: "min-heap-max-heap",
            title: "Min Heap and Max Heap Implementation",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/min-heap-and-max-heap-implementation/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/min-heap-and-max-heap-implementation",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-heap/",
          },
        ],
      },
      {
        id: "lec-11-2",
        title: "Medium Problems",
        problems: [
          {
            id: "kth-largest-element",
            title: "Kth Largest Element in an Array",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/kth-largest-element-in-an-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            leetcodeUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/k-largestor-smallest-elements-in-an-array/",
          },
          {
            id: "k-most-frequent-elements",
            title: "K Most Frequent Elements",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/k-most-frequent-elements/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-k-numbers-occurrences-given-array/",
          },
        ],
      },
      {
        id: "lec-11-3",
        title: "Hard Problems",
        problems: [
          {
            id: "merge-k-sorted-lists",
            title: "Merge K Sorted Lists",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/merge-k-sorted-lists/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            leetcodeUrl: "https://leetcode.com/problems/merge-k-sorted-lists/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/",
          },
          {
            id: "find-median-data-stream",
            title: "Find Median from Data Stream",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/find-median-from-data-stream/",
            youtubeUrl: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            leetcodeUrl: "https://leetcode.com/problems/find-median-from-data-stream/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-median-of-stream-of-running-integers/",
          },
        ],
      },
    ],
  },
  {
    id: "step-12",
    stepNumber: 12,
    title: "Greedy Algorithms [Easy, Medium/Hard Problems]",
    description: "Master greedy algorithm paradigm",
    totalProblems: 16,
    lectures: [
      {
        id: "lec-12-1",
        title: "Easy Problems",
        problems: [
          {
            id: "assign-cookies",
            title: "Assign Cookies",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/greedy-algorithm/assign-cookies/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            leetcodeUrl: "https://leetcode.com/problems/assign-cookies/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/assign-cookies-problem/",
          },
          {
            id: "fractional-knapsack",
            title: "Fractional Knapsack",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/fractional-knapsack-problem-greedy-approach",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/fractional-knapsack-problem/",
          },
          {
            id: "minimum-coins",
            title: "Minimum number of Coins",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/find-minimum-number-of-coins/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/find-minimum-number-of-coins",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/",
          },
        ],
      },
      {
        id: "lec-12-2",
        title: "Medium/Hard Problems",
        problems: [
          {
            id: "job-sequencing-problem",
            title: "Job Sequencing Problem",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/job-sequencing-problem/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/job-sequencing-problem",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/job-sequencing-problem/",
          },
          {
            id: "jump-game",
            title: "Jump Game",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/jump-game/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            leetcodeUrl: "https://leetcode.com/problems/jump-game/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/",
          },
          {
            id: "jump-game-ii",
            title: "Jump Game II",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/jump-game-ii/",
            youtubeUrl: "https://www.youtube.com/watch?v=DIX2p7vb9co",
            leetcodeUrl: "https://leetcode.com/problems/jump-game-ii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/",
          },
        ],
      },
    ],
  },
  {
    id: "step-13",
    stepNumber: 13,
    title: "Binary Trees [Traversals, Medium and Hard Problems]",
    description: "Complete binary tree mastery",
    totalProblems: 39,
    lectures: [
      {
        id: "lec-13-1",
        title: "Traversals",
        problems: [
          {
            id: "intro-to-trees",
            title: "Introduction to Trees",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/binary-tree/introduction-to-trees/",
            youtubeUrl: "https://www.youtube.com/watch?v=BHB0B1jFKPY",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-tree-data-structure/",
          },
          {
            id: "binary-tree-representation",
            title: "Binary Tree Representation in C++",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/binary-tree/binary-tree-representation-in-c/",
            youtubeUrl: "https://www.youtube.com/watch?v=BHB0B1jFKPY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/binary-tree-representation-in-c",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-tree-array-implementation/",
          },
          {
            id: "binary-tree-traversals",
            title: "Binary Tree Traversals: Inorder, Preorder, Postorder",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/binary-tree-traversal-inorder-preorder-postorder/",
            youtubeUrl: "https://www.youtube.com/watch?v=BHB0B1jFKPY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/binary-tree-traversal-inorder-preorder-postorder",
            leetcodeUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/",
          },
        ],
      },
      {
        id: "lec-13-2",
        title: "Medium Problems",
        problems: [
          {
            id: "height-of-binary-tree",
            title: "Maximum Depth of Binary Tree",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/maximum-depth-of-a-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/",
          },
          {
            id: "balanced-binary-tree",
            title: "Balanced Binary Tree",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/check-if-the-binary-tree-is-balanced-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            leetcodeUrl: "https://leetcode.com/problems/balanced-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/how-to-determine-if-a-binary-tree-is-balanced/",
          },
          {
            id: "diameter-of-binary-tree",
            title: "Diameter of Binary Tree",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/",
          },
        ],
      },
      {
        id: "lec-13-3",
        title: "Hard Problems",
        problems: [
          {
            id: "lowest-common-ancestor",
            title: "Lowest Common Ancestor in Binary Tree",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/lowest-common-ancestor-binary-tree-set-1/",
          },
          {
            id: "serialize-deserialize-binary-tree",
            title: "Serialize and Deserialize Binary Tree",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/serialize-and-deserialize-a-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            leetcodeUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/",
          },
          {
            id: "morris-traversal",
            title: "Morris Traversal | Preorder | Inorder",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/morris-inorder-traversal-of-a-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=eD3tmO66aBA",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/morris-inorder-traversal-of-a-binary-tree",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion-and-without-stack/",
          },
        ],
      },
    ],
  },
  {
    id: "step-14",
    stepNumber: 14,
    title: "Binary Search Trees [Concept and Problems]",
    description: "Master Binary Search Trees",
    totalProblems: 16,
    lectures: [
      {
        id: "lec-14-1",
        title: "Concepts",
        problems: [
          {
            id: "intro-to-bst",
            title: "Introduction to Binary Search Trees",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/binary-search-tree/introduction-to-binary-search-trees/",
            youtubeUrl: "https://www.youtube.com/watch?v=p7-9UvDQZ3w",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-search-tree-data-structure/",
          },
          {
            id: "search-in-bst",
            title: "Search in a Binary Search Tree",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/binary-search-tree/search-in-a-binary-search-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=p7-9UvDQZ3w",
            leetcodeUrl: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/binary-search-tree-set-1-search-and-insertion/",
          },
        ],
      },
      {
        id: "lec-14-2",
        title: "Practice Problems",
        problems: [
          {
            id: "validate-bst",
            title: "Validate Binary Search Tree",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/check-if-a-tree-is-a-binary-search-tree-or-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=p7-9UvDQZ3w",
            leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/",
          },
          {
            id: "lca-in-bst",
            title: "LCA in Binary Search Tree",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/lca-in-binary-search-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=p7-9UvDQZ3w",
            leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/",
          },
        ],
      },
      {
        id: "lec-14-3",
        title: "Hard Problems",
        problems: [
          {
            id: "largest-bst-in-binary-tree",
            title: "Largest BST in Binary Tree",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/largest-bst-in-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=p7-9UvDQZ3w",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/largest-bst-in-binary-tree",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/largest-bst-binary-tree-set-2/",
          },
        ],
      },
    ],
  },
  {
    id: "step-15",
    stepNumber: 15,
    title: "Graphs [Concepts & Problems]",
    description: "Complete graph algorithms mastery",
    totalProblems: 54,
    lectures: [
      {
        id: "lec-15-1",
        title: "Learning",
        problems: [
          {
            id: "intro-to-graphs",
            title: "Introduction to Graphs",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/graph/introduction-to-graphs/",
            youtubeUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
          },
          {
            id: "graph-representation",
            title: "Graph Representation | C++",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/graph/graph-representation-adjacency-list-and-matrix/",
            youtubeUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/graph-representation-adjacency-list-and-matrix",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/graph-and-its-representations/",
          },
        ],
      },
      {
        id: "lec-15-2",
        title: "BFS/DFS Problems",
        problems: [
          {
            id: "bfs-traversal",
            title: "BFS of Graph",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/",
            youtubeUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/breadth-first-search-bfs-level-order-traversal",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/",
          },
          {
            id: "dfs-traversal",
            title: "DFS of Graph",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/depth-first-search-dfs/",
            youtubeUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/depth-first-search-dfs",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
          },
          {
            id: "number-of-provinces",
            title: "Number of Provinces",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/number-of-provinces/",
            youtubeUrl: "https://www.youtube.com/watch?v=M3_pLsDdeuU",
            leetcodeUrl: "https://leetcode.com/problems/number-of-provinces/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/find-the-number-of-islands-using-dfs/",
          },
        ],
      },
      {
        id: "lec-15-3",
        title: "Shortest Path Algorithms",
        problems: [
          {
            id: "dijkstra-algorithm",
            title: "Dijkstra's Algorithm",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/dijkstras-algorithm-shortest-path/",
            youtubeUrl: "https://www.youtube.com/watch?v=jbhuqIASjoM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/dijkstras-algorithm-shortest-path",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
          },
          {
            id: "bellman-ford-algorithm",
            title: "Bellman Ford Algorithm",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/bellman-ford-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=jbhuqIASjoM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/bellman-ford-algorithm",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/",
          },
          {
            id: "floyd-warshall-algorithm",
            title: "Floyd Warshall Algorithm",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/floyd-warshall-algorithm/",
            youtubeUrl: "https://www.youtube.com/watch?v=jbhuqIASjoM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/floyd-warshall-algorithm",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/",
          },
        ],
      },
      {
        id: "lec-15-4",
        title: "MST/Disjoint Set and Problems",
        problems: [
          {
            id: "disjoint-set-union-find",
            title: "Disjoint Set | Union by Rank | Union by Size | Path Compression",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/",
            youtubeUrl: "https://www.youtube.com/watch?v=jbhuqIASjoM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/disjoint-set-union-by-rank-union-by-size-path-compression-g-46",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/union-find/",
          },
          {
            id: "kruskals-algorithm",
            title: "Kruskal's Algorithm",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=jbhuqIASjoM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/kruskals-algorithm-minimum-spanning-tree",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
          },
        ],
      },
    ],
  },
  {
    id: "step-16",
    stepNumber: 16,
    title: "Dynamic Programming [Patterns and Problems]",
    description: "Complete DP mastery with all patterns",
    totalProblems: 56,
    lectures: [
      {
        id: "lec-16-1",
        title: "Introduction to DP",
        problems: [
          {
            id: "intro-to-dp",
            title: "Introduction to Dynamic Programming",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/dynamic-programming/introduction-to-dynamic-programming/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/dynamic-programming/",
          },
          {
            id: "fibonacci-dp",
            title: "Fibonacci | DP",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/dynamic-programming-fibonacci-number/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/dynamic-programming-fibonacci-number",
            leetcodeUrl: "https://leetcode.com/problems/fibonacci-number/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/",
          },
        ],
      },
      {
        id: "lec-16-2",
        title: "1D DP",
        problems: [
          {
            id: "climbing-stairs",
            title: "Climbing Stairs",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/dynamic-programming-climbing-stairs/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
          },
          {
            id: "house-robber",
            title: "House Robber",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/maximum-sum-of-non-adjacent-elements-dp-5/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/house-robber/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/",
          },
        ],
      },
      {
        id: "lec-16-3",
        title: "2D/3D DP and DP on Grids",
        problems: [
          {
            id: "unique-paths",
            title: "Unique Paths",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/grid-unique-paths-dp-on-grids-dp8/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/unique-paths/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/count-possible-paths-top-left-bottom-right-nxm-matrix/",
          },
          {
            id: "unique-paths-ii",
            title: "Unique Paths II",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/grid-unique-paths-2-dp-9/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/unique-paths-ii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/unique-paths-in-a-grid-with-obstacles/",
          },
          {
            id: "minimum-path-sum",
            title: "Minimum Path Sum",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/minimum-path-sum-in-a-grid-dp-10/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/minimum-path-sum/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/minimum-sum-path-in-a-triangle/",
          },
        ],
      },
      {
        id: "lec-16-4",
        title: "DP on Subsequences",
        problems: [
          {
            id: "subset-sum-equal-k",
            title: "Subset Sum Equal To K",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/subset-sum-equal-to-target-dp-14/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/subset-sum-equal-to-target-dp-14",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/",
          },
          {
            id: "partition-equal-subset-sum",
            title: "Partition Equal Subset Sum",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/partition-equal-subset-sum-dp-15/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/partition-equal-subset-sum/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/partition-problem-dp-18/",
          },
        ],
      },
      {
        id: "lec-16-5",
        title: "DP on Strings",
        problems: [
          {
            id: "longest-common-subsequence",
            title: "Longest Common Subsequence",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/longest-common-subsequence-dp-25/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/longest-common-subsequence/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
          },
          {
            id: "longest-palindromic-subsequence",
            title: "Longest Palindromic Subsequence",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/longest-palindromic-subsequence-dp-28/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-subsequence/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/",
          },
          {
            id: "edit-distance",
            title: "Edit Distance",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/edit-distance-dp-33/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/edit-distance/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/edit-distance-dp-5/",
          },
        ],
      },
      {
        id: "lec-16-6",
        title: "DP on Stocks",
        problems: [
          {
            id: "best-time-buy-sell-stock",
            title: "Best Time to Buy and Sell Stock",
            difficulty: "Easy",
            tufUrl: "https://takeuforward.org/data-structure/stock-buy-and-sell-dp-35/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/",
          },
          {
            id: "best-time-buy-sell-stock-ii",
            title: "Best Time to Buy and Sell Stock II",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/buy-and-sell-stocks-with-transaction-fees-dp-40/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/stock-buy-sell/",
          },
        ],
      },
      {
        id: "lec-16-7",
        title: "DP on LIS",
        problems: [
          {
            id: "longest-increasing-subsequence",
            title: "Longest Increasing Subsequence",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/",
          },
          {
            id: "printing-longest-increasing-subsequence",
            title: "Printing Longest Increasing Subsequence",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/printing-longest-increasing-subsequence-dp-42/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/printing-longest-increasing-subsequence-dp-42",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/construction-of-longest-increasing-subsequence-n-log-n/",
          },
        ],
      },
      {
        id: "lec-16-8",
        title: "MCM DP | Partition DP",
        problems: [
          {
            id: "matrix-chain-multiplication",
            title: "Matrix Chain Multiplication",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/matrix-chain-multiplication-dp-48",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/",
          },
          {
            id: "burst-balloons",
            title: "Burst Balloons",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/burst-balloons-partition-dp-dp-51/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/burst-balloons/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/burst-balloon-to-maximize-coins/",
          },
        ],
      },
      {
        id: "lec-16-9",
        title: "DP on Trees",
        problems: [
          {
            id: "diameter-of-binary-tree-dp",
            title: "Diameter of Binary Tree",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=tyB0ztf0DNY",
            leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/",
          },
        ],
      },
    ],
  },
  {
    id: "step-17",
    stepNumber: 17,
    title: "Tries",
    description: "Master Trie data structure",
    totalProblems: 7,
    lectures: [
      {
        id: "lec-17-1",
        title: "Theory",
        problems: [
          {
            id: "implement-trie",
            title: "Implement Trie (Prefix Tree)",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/implement-trie-prefix-tree/",
            youtubeUrl: "https://www.youtube.com/watch?v=dBGUmUQhjaM",
            leetcodeUrl: "https://leetcode.com/problems/implement-trie-prefix-tree/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/trie-insert-and-search/",
          },
          {
            id: "implement-trie-ii",
            title: "Implement Trie - 2 (Prefix Tree)",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/implement-trie-2/",
            youtubeUrl: "https://www.youtube.com/watch?v=dBGUmUQhjaM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/implement-trie-2",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/trie-insert-and-search/",
          },
        ],
      },
      {
        id: "lec-17-2",
        title: "Problems",
        problems: [
          {
            id: "longest-word-with-all-prefixes",
            title: "Longest Word With All Prefixes",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/longest-word-with-all-prefixes/",
            youtubeUrl: "https://www.youtube.com/watch?v=dBGUmUQhjaM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/longest-word-with-all-prefixes",
            leetcodeUrl: "https://leetcode.com/problems/longest-word-in-dictionary/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/longest-word-dictionary-deleting-characters-given-string/",
          },
          {
            id: "count-distinct-substrings",
            title: "Count Distinct Substrings",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/count-distinct-substrings-using-trie/",
            youtubeUrl: "https://www.youtube.com/watch?v=dBGUmUQhjaM",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/count-distinct-substrings-using-trie",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/count-distinct-substrings-string-using-suffix-array/",
          },
          {
            id: "maximum-xor-of-two-numbers",
            title: "Maximum XOR of two numbers in an array",
            difficulty: "Medium",
            tufUrl: "https://takeuforward.org/data-structure/maximum-xor-of-two-numbers-in-an-array/",
            youtubeUrl: "https://www.youtube.com/watch?v=dBGUmUQhjaM",
            leetcodeUrl: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/maximum-xor-of-two-numbers-in-an-array/",
          },
        ],
      },
    ],
  },
  {
    id: "step-18",
    stepNumber: 18,
    title: "Strings Part-II",
    description: "Advanced string algorithms and techniques",
    totalProblems: 5,
    lectures: [
      {
        id: "lec-18-1",
        title: "Hard Problems",
        problems: [
          {
            id: "z-function",
            title: "Z-Function",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/z-function/",
            youtubeUrl: "https://www.youtube.com/watch?v=CpZh4eF8QBw",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/z-function",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/z-algorithm-linear-time-pattern-searching-algorithm/",
          },
          {
            id: "kmp-algorithm",
            title: "KMP Algorithm | LPS(Longest Prefix Suffix)",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/kmp-algorithm-longest-prefix-suffix/",
            youtubeUrl: "https://www.youtube.com/watch?v=CpZh4eF8QBw",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/kmp-algorithm-longest-prefix-suffix",
            leetcodeUrl: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/",
          },
          {
            id: "minimum-characters-palindrome",
            title: "Minimum Characters needed to make a String Palindrome",
            difficulty: "Hard",
            tufUrl: "https://takeuforward.org/data-structure/minimum-characters-needed-to-make-a-string-palindrome/",
            youtubeUrl: "https://www.youtube.com/watch?v=CpZh4eF8QBw",
            practiceUrl: "https://takeuforward.org/plus/dsa/problems/minimum-characters-needed-to-make-a-string-palindrome",
            geeksforgeeksUrl: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/",
          },
        ],
      },
    ],
  },
];

// Continue with remaining steps: Recursion, Bit Manipulation, Stack/Queue, etc.
// Total should reach 455 problems across all 18 steps

export const getAllProblems = () => {
  const problems = [];
  for (const step of dsaSteps) {
    for (const lecture of step.lectures) {
      problems.push(...lecture.problems);
    }
  }
  return problems;
};

export const getProblemsByDifficulty = (difficulty: "Easy" | "Medium" | "Hard") => {
  return getAllProblems().filter(problem => problem.difficulty === difficulty);
};

export const getTotalProblemCounts = () => {
  const all = getAllProblems();
  return {
    total: all.length,
    easy: all.filter(p => p.difficulty === "Easy").length,
    medium: all.filter(p => p.difficulty === "Medium").length,
    hard: all.filter(p => p.difficulty === "Hard").length,
  };
};
